# 3 errores identificables por flake8; errores.py

def func(x):
    print(x)
    return x + 1


func(3)
